name: Publish to npm

on:
  push:
    branches:
      - main
    # Don't trigger on CHANGELOG.md updates to avoid loops
    paths-ignore:
      - 'CHANGELOG.md'
      - '**/README.md'
  workflow_dispatch:
    # This enables manual triggering

# Explicitly set permissions for the GITHUB_TOKEN
permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Generate new version
        run: |
          # Skip version bump if the commit is a release commit
          if [[ $(git log -1 --pretty=%B) != "chore(release): "* ]]; then
            npx standard-version
          fi

      - name: Push changes
        run: |
          # Push with skip ci flag to prevent recursion
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}
          git commit --amend -m "$(git log -1 --pretty=%B) [skip ci]"
          git push && git push --follow-tags origin main

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
